#!/usr/bin/env python3

# Generate usys.S equivalent to usys.pl

print("# generated by generate_usys.py - do not edit")
print("#include \"kernel/syscall.h\"")

def entry(name):
    prefix = "sys_"
    if name == "sbrk":
        print(f".global {prefix}{name}")
        print(f"{prefix}{name}:")
    else:
        print(f".global {name}")
        print(f"{name}:")
    print(f" li a7, SYS_{name}")
    print(" ecall")
    print(" ret")

entries = [
    "fork", "exit", "wait", "pipe", "read", "kill", "exec", "fstat",
    "chdir", "dup", "getpid", "sbrk", "hapinfo", "pause", "uptime",
    "open", "write", "mknod", "unlink", "link", "mkdir", "close"
]

for e in entries:
    entry(e)
